"""Walk-forward retention and a permutation test for timing.

Two checks that ask different questions from the Sharpe-based ones:

* **Walk-forward** -- if I re-pick the best configuration on each expanding
  training window and only ever trade the next window, what is left? The ratio
  of that to the full-sample optimised Sharpe is how much of the edge survives
  honest selection.

* **Permutation** -- does the strategy's *timing* beat a random phase shift of
  the same positions? This separates "I was in the market at the right moments"
  from "I was in the market a lot, and the market went up".
"""

from __future__ import annotations

import math
from typing import Dict, List, Sequence, Tuple

import numpy as np

from .sharpe import per_period_sharpe

__all__ = ["walk_forward_from_matrix", "monte_carlo_permutation"]


def walk_forward_from_matrix(
    returns_matrix, n_folds: int = 6, periods_per_year: int = 252
) -> Dict[str, object]:
    """Expanding-window walk-forward over a precomputed matrix of trials.

    For each fold ``k > 0``: choose the column with the best Sharpe on folds
    ``0..k-1``, then record that column's returns on fold ``k``. Fold ``k`` was
    never used to make the choice, so the stitched series is genuinely
    out-of-sample.

    Returns a dict with ``oos_returns``, ``oos_sharpe`` (annualised),
    ``is_best_sharpe`` (full-sample optimised, annualised) and ``degradation``
    -- the fraction of the in-sample Sharpe retained, clipped to [0, 1].

    Notes
    -----
    ``degradation`` is only meaningful when the in-sample optimum is positive.
    If the best in-sample configuration already loses money there is nothing to
    retain, so retention is 0 regardless of a lucky positive out-of-sample draw.
    """
    M = np.asarray(returns_matrix, dtype=float)
    if M.ndim != 2:
        raise ValueError("returns_matrix must be 2-D, shape (T, N)")

    T, N = M.shape
    folds = np.array_split(np.arange(T), n_folds)

    oos_chunks: List[np.ndarray] = []
    for k in range(1, n_folds):
        train = np.concatenate(folds[:k])
        test = folds[k]
        if len(train) < 2 or len(test) == 0:
            continue
        train_sh = np.array([per_period_sharpe(M[train, j]) for j in range(N)])
        best = int(np.argmax(train_sh))
        oos_chunks.append(M[test, best])

    oos = np.concatenate(oos_chunks) if oos_chunks else np.array([])
    oos_sharpe = per_period_sharpe(oos) * math.sqrt(periods_per_year)

    full_sh = np.array([per_period_sharpe(M[:, j]) for j in range(N)])
    is_best = float(full_sh.max()) * math.sqrt(periods_per_year)

    if not math.isfinite(oos_sharpe):
        degradation = float("nan")
    elif is_best > 0:
        degradation = max(0.0, min(1.0, oos_sharpe / is_best))
    else:
        degradation = 0.0

    return {
        "oos_returns": oos,
        "oos_sharpe": oos_sharpe,
        "is_best_sharpe": is_best,
        "degradation": degradation,
    }


def monte_carlo_permutation(
    positions: Sequence[float],
    asset_returns: Sequence[float],
    cost_rate: float = 0.0005,
    n_iter: int = 1000,
    seed: int = 0,
) -> Tuple[float, float, np.ndarray]:
    """Test whether the strategy's timing beats a random phase shift.

    Returns ``(p_value, observed_sharpe, null_distribution)``.

    The null is generated by **circularly shifting** the position series, not by
    shuffling it. A circular shift preserves both the run-length structure
    (autocorrelation) and the turnover, so the only thing destroyed is the
    *alignment* between positions and returns. An i.i.d. shuffle would shatter
    trend runs and inflate turnover, making the null artificially weak and the
    p-value artificially small.

    A small p means the alignment is doing real work.

    Notes
    -----
    Returns NaN when the position series changes at most once. Every circular
    shift of "enter once and hold" produces the same result, so the test would
    report a damning p ≈ 1 for what is simply buy-and-hold. There is no timing
    to test, and saying so is better than scoring it.
    """
    pos = np.asarray(positions, dtype=float)
    ar = np.asarray(asset_returns, dtype=float)
    if pos.shape != ar.shape:
        raise ValueError(
            f"positions {pos.shape} and asset_returns {ar.shape} must align"
        )

    def _sharpe_of(p: np.ndarray) -> float:
        cost = cost_rate * np.abs(np.diff(p, prepend=0.0))
        return per_period_sharpe(p * ar - cost)

    observed = _sharpe_of(pos)
    n = len(pos)

    if int((np.diff(pos) != 0).sum()) <= 1:
        return float("nan"), float(observed), np.array([])

    rng = np.random.default_rng(seed)
    null = np.full(n_iter, observed, dtype=float)
    if n > 2:
        offsets = rng.integers(1, n, size=n_iter)
        for i, off in enumerate(offsets):
            null[i] = _sharpe_of(np.roll(pos, int(off)))

    # +1 in numerator and denominator: the observed value is itself one draw from
    # the null, so a p-value of exactly 0 is not attainable and should not be.
    p_value = (np.sum(null >= observed) + 1.0) / (n_iter + 1.0)
    return float(p_value), float(observed), null
